console.log("Witaj w liście najlepszych skrótów klawiaturowych programu VSC!");
console.log("Najważniejszym skrótem jest CTRL + S. Pozwala on na zapisanie zmian w pliku. Nie zapomnij go używać!");
console.log("Lewy alt plus strzałka w górę/w dół pozwa przenieść aktualnie zaznaczony wiersz w górę lub w dół.");
console.log("Lewy ctrl plus klawisz super plus strzałka w górę/w dół pozwala kopiować aktualnie zaznaczony wiersz w górę lub w dół. ");
console.log("Lewy alt plus prawy klawisz myszy pozwala dodawać kolejne kursory. ");
console.log("Lewy ctrl plus znak zapytania pozwala zakomentować linię. ");
console.log("Lewy ctrl plus F pozwala znaleźć szukaną frazę w dokumencie. ");
console.log("Lewy ctrl plus O pozwala otworzyć plik. ");
console.log("Lewy ctrl plus home/end pozwa przejść na początek/koniec dokumentu. ");
console.log("Lewy ctrl plus H pozwala podmienić zaznaczaony fragment tekstu. ");
console.log("Lewy ctrl plus tylda otwiera nowy terminal. ");